# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "L'Hermine Végane"
email: hermine.vegane@sent.com
description: >- # this means to ignore newlines until "baseurl:"
  L'Hermine Végane essaie de partager en simplicité des informations trop souvent tues
  sur des sujets tels que la santé, l'alimentation et surtout le véganisme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://veganisme.adriengiboire.com" # the base hostname & protocol for your site, e.g. http://example.com
socials:
  twitter:
    link: https://x.com/adriengiboire
    username: adriengiboire
    icon: twitter
  facebook:
    link: https://facebook.com/adriengiboire
    username: adriengiboire
    icon: facebook
  instagram:
    link: https://instagram.com/adriengiboire
    username: adriengiboire
    icon: instagram
  youtube:
    link: https://www.youtube.com/adriengiboire
    username: "Adrien Giboire - La vie d'un végane"
    icon: youtube

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
